version: 2.1

jobs:
  build:
    working_directory: ~/repo/react-native-sportlight-tour
    
    machine:
      docker_layer_caching: true
      image: circleci/classic:latest

    steps:
      - checkout:
          path: ~/repo/react-native-sportlight-tour

      - run:
          name: Setup NVM
          command: |
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Install NodeJS
          command: |
            nvm install
            nvm use
            nvm alias default node

      - run:
          name: Install Yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
            echo 'export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV

      - restore_cache:
          keys:
            - v1-node-modules-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-node-modules-{{ .Branch }}-
            - v1-node-modules-

      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          key: v1-node-modules-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Compile
          command: yarn compile

workflows:
  build-and-check:
    jobs:
      - build
