version: 2.1
orbs:
  node: 'circleci/node@4.1.0'

jobs:
  build:
    working_directory: ~/repo/react-native-sportlight-tour

    executor:
      name: node/default
      tag: '14.7'

    steps:
      - checkout
      - node/install:
          node-version: '14.7.0'
          install-npm: false
          install-yarn: true
          yarn-version: '1.22.4'

      - node/install-packages:
          pkg-manager: yarn

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Compile
          command: yarn compile

      - run:
          name: Tests
          command: yarn test

workflows:
  build-and-check:
    jobs:
      - build
