version: 2.1
orbs:
  node: 'circleci/node@4.3.0'

jobs:
  build:
    working_directory: ~/repo/react-native-sportlight-tour

    executor:
      name: node/default
      tag: '17.3.0'

    steps:
      - checkout

      - node/install:
          node-version: '17.3.0'
          install-npm: false
          install-yarn: true
          yarn-version: '1.22.17'

      - node/install-packages:
          pkg-manager: yarn

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Compile
          command: yarn compile

      - run:
          name: Tests
          command: yarn test

  publish:
    working_directory: ~/repo/react-native-sportlight-tour

    executor:
      name: node/default
      tag: '17.3.0'

    steps:
      - checkout

      - node/install:
          node-version: '17.3.0'
          install-npm: false
          install-yarn: true
          yarn-version: '1.22.17'

      - node/install-packages:
          pkg-manager: yarn

      - run:
          name: Compile
          command: yarn compile

      - run:
          name: Publish
          command: yarn semantic-release


workflows:
  main:
    jobs:
      - build

      - publish:
          requires:
            - build
          filters:
            branches:
              only: release
