version: 2.1
orbs:
  node: 'circleci/node@4.3.0'

jobs:
  build:
    working_directory: ~/repo/react-native-sportlight-tour

    executor:
      name: node/default
      tag: '16.0'

    steps:
      - checkout

      - node/install:
          node-version: '16.0.0'
          install-npm: false
          install-yarn: true
          yarn-version: '1.22.5'

      - node/install-packages:
          pkg-manager: yarn

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Compile
          command: yarn compile

      - run:
          name: Tests
          command: yarn test

  release:
    working_directory: ~/repo/react-native-sportlight-tour

    executor:
      name: node/default
      tag: '16.0'

    steps:
      - checkout

      - node/install:
          node-version: '16.0.0'
          install-npm: true
          install-yarn: true
          yarn-version: '1.22.5'

      - node/install-packages:
          pkg-manager: yarn

      - run:
          name: Compile
          command: yarn compile

      - run:
          name: NPM Registry Auth
          command: npm set //registry.npmjs.org/:_authToken $NPM_TOKEN

      - run:
          name: Publish
          command: npm publish


workflows:
  main:
    jobs:
      - build

      - release:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/
