---
name: Release

on:
  push:
    branches: [release]

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/ci.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: yarn
      - run: yarn install --immutable
      - run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  pages:
    uses: ./.github/workflows/pages.yml
    needs: [deploy]
